
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: false
    # 超过这个时间没收到心跳就剔除这个服务，这个配置一般为服务刷新时间配置的三倍，默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间，默认30s
    lease-renewal-interval-in-seconds: 5
  server:
    enable-self-preservation: false
    # 服务下线任务定时，默认60s
    eviction-interval-timer-in-ms: 5000
    # eureka server刷新readCacheMap的时间,client读取的是readCacheMap,默认30s
    response-cache-update-interval-ms: 3000
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      default-zone: http://192.168.1.7:${server.port}/eurekaservice/eureka/
logging:
  config: classpath:log4j2.xml
